### ISSUE TITLE
`@keyframes :global()` selector not properly handled in CSS modules - Unexpected token Colon 

### ISSUE THREAD

**Issue by jantimon** [parcel-bundler/lightningcss#863] opened 2024-12-03 12:05 UTC
When using the `:global()` selector with `@keyframes` the animation name cannot be parsed and LightningCSS throws a syntax error `Unexpected token Colon`

#### Example CSS
```css
@keyframes :global(foo) {
  to {
    opacity: 1
  }
}
```

#### Current Behavior

**`Unexpected token Colon`**

#### Expected Behavior
Same result as PostCSS ([Stackblitz Demo](https://stackblitz.com/edit/node-faevj5?file=index.js)):
```css
@keyframes foo {
  to {
    opacity: 1
  }
}
```

**Comment by devongovett** [comment] 2024-12-16 18:35
Duplicate of #825. This syntax is not supported.

**Closed by devongovett** 2024-12-16 18:35 UTC

**Comment by jantimon** [comment] 2024-12-18 06:49
Okay - I really like the idea of `@global` - do you think it makes sense to start working on a `@global` pr?

What about using global keyframes?
That's not possible with `@global`

postcss supports the following syntax:

```css
animation: global(animation-name);
```

postcss allows mixing it with non global animation names in the same declaration

**Comment by devongovett** [comment] 2024-12-18 07:01
The "referencing an identifier" section of the proposal has a more general way to do that which would allow importing names from other files in addition to the global namespace.

**Comment by jantimon** [comment] 2024-12-18 12:35
okay so instead of 

```css
animation: global(animation-name);
```

you would prefer

```css
animation-name: import(fade from global);
```

do you think we could already implement `import(XXX from global)`?  
in that case I would create an issue and a pr

**Comment by devongovett** [comment] 2024-12-18 16:20
Not sure. It was just a proposal. I was hoping to get consensus between implementations. Sounds like postcss implemented `global()` recently? Do they have a way to use an animation name defined in another file?

**Comment by jantimon** [comment] 2024-12-19 08:51
That's correct - it was added last month

![shot-r5arj7bq@2x](https://github.com/user-attachments/assets/affad384-9e08-4f30-9c4c-e76e9a4b42bf)

Right now it's not possible in postcss to import an identifier from another file so the only solution is defining it global either in a non css module or using `:global()` like this:

```css
@keyframes :global(fade-in) {
  
}
```

once defined it can be consume with `global()` from another file:

```css
animation: global(animation-name);
```

`global()` also allows using pre defined keyframes from libraries like https://animate.style/ or [open-props](https://github.com/argyleink/open-props/blob/main/src/props.animations.css)

and `global()` also allows using page wide defined animations which can be used in different islands
