### ISSUE TITLE
cli: mis-match between --version and npm package version

### ISSUE THREAD

**Issue by jprjr** [parcel-bundler/lightningcss#740] opened 2024-05-13 18:52 UTC
Hi there - I noticed that when I run `lightningcss --version`, I get back the version as reported in the `Cargo.toml` file, like:

```
$ lightningcss  --version
lightningcss 1.0.0-alpha.55
```

My expectation would be to match the version listed in the package.json file (currently `1.24.1`)

**Comment by devongovett** [comment] 2024-05-14 05:39
dupe of #322

**Closed by devongovett** 2024-05-14 05:39 UTC
