### ISSUE TITLE
lightningcss transform problem

### ISSUE THREAD

**Issue by ysy945** [parcel-bundler/lightningcss#550] opened 2023-07-26 03:24 UTC
<img width="1327" alt="image" src="https://github.com/parcel-bundler/lightningcss/assets/79794654/6050752a-afd5-4de0-8a70-efcd00f3457f">
- "less-loader" will generator code like this.but through lightningcss will transformm  right code.the right code could't transform by 'css-loader'. the error may 
<img width="1430" alt="image" src="https://github.com/parcel-bundler/lightningcss/assets/79794654/1e758f72-26f3-4e06-a294-4bb9eeca0687">

- hoping generator
```css
.wrap :global .xgplayer-skin-default {
  display: none;
}

.hide-live-wrapper {
  display: none;
}
```
instead
```css
.wrap :global .xgplayer-skin-default, .hide-live-wrapper {
  display: none;
}
```

**Comment by devongovett** [comment] 2023-08-20 00:01
Lightning CSS does not currently implement the `:global` or `:local` selectors without an argument, because it's hard to parse and works differently from all other pseudo classes. Also, I generally think the syntax is pretty weird and the function syntax is much easier to read. See https://github.com/parcel-bundler/parcel-css/issues/6#issuecomment-1025324354 for more comments.

Going to close as a duplicate of #6.

**Closed by devongovett** 2023-08-20 00:01 UTC
