### ISSUE TITLE
Use browserslist entry in package.json with lightningcss-cli

### ISSUE THREAD

**Issue by makkabi** [parcel-bundler/lightningcss#293] opened 2022-09-16 18:54 UTC
When using the lightningcss-cli, the only way to provide a browserslist target seems to be the --target option, while the browserslist entry in package.json (and also a .browserslistrc file) is beeing ignored.  This means having to duplicate the browserslist target, but it would be much nicer if the lightningcss-cli would use the single definition in package.json like many other tools. The --target option could override the entry in package.json.

**Comment by toastal** [comment] 2022-09-18 08:08
Looks like this could be a duplicate of #281

**Comment by LeoniePhiline** [comment] 2022-10-24 12:25
I'll see if I can fix that.

**Comment by toastal** [comment] 2022-10-25 01:20
@LeoniePhiline if you do, could you look at #281 too (`$PWD/.browserslistrc`)? If someone is using the Rust binary without npm, it would be weird to include a `package.json` just for `browserslist`.

**Closed** 2022-11-06 04:20 UTC
Labels: enhancement, good first issue
